-- Insertar nuevos destinos turísticos

-- Cayos de Chichiriviche
INSERT INTO public.destinations (name, slug, description, full_description, location, price, duration, departure_location, image_url, gallery_urls, highlights, includes) VALUES
('Cayo Sombrero', 'cayo-sombrero', 'Paraíso caribeño con aguas cristalinas y arena blanca', 'Experimenta un día inolvidable en uno de los cayos más hermosos del Caribe venezolano. Cayo Sombrero te ofrece aguas turquesas cristalinas, arena blanca y un ambiente paradisíaco perfecto para relajarte y disfrutar del sol.', 'Chichiriviche, Falcón', 120.00, '1 día (5:00 AM - 7:00 PM)', 'Plaza Venezuela, Caracas', 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop', ARRAY['https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop'], ARRAY['Aguas cristalinas', 'Playa de arena blanca', 'Snorkeling', 'Ambiente tranquilo'], ARRAY['Transporte ida y vuelta', 'Transporte marítimo', 'Almuerzo', 'Snacks', 'Guía turístico', 'Equipo de snorkeling']),

('Cayo Sal', 'cayo-sal', 'Isla virgen perfecta para el descanso total', 'Descubre la tranquilidad absoluta en Cayo Sal, una isla virgen donde podrás desconectarte del mundo y conectarte con la naturaleza. Ideal para quienes buscan paz y belleza natural.', 'Chichiriviche, Falcón', 110.00, '1 día (5:00 AM - 7:00 PM)', 'Plaza Venezuela, Caracas', 'https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?w=800&h=600&fit=crop', ARRAY['https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?w=800&h=600&fit=crop'], ARRAY['Isla virgen', 'Tranquilidad absoluta', 'Aguas transparentes', 'Flora y fauna marina'], ARRAY['Transporte ida y vuelta', 'Transporte marítimo', 'Almuerzo típico', 'Bebidas', 'Guía turístico']),

('Cayo Peraza', 'cayo-peraza', 'Aventura marina con arrecifes de coral', 'Vive una experiencia única en Cayo Peraza, conocido por sus increíbles arrecifes de coral y biodiversidad marina. Perfecto para los amantes del snorkeling y buceo.', 'Chichiriviche, Falcón', 115.00, '1 día (5:00 AM - 7:00 PM)', 'Plaza Venezuela, Caracas', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop', ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop'], ARRAY['Arrecifes de coral', 'Biodiversidad marina', 'Snorkeling premium', 'Aguas cálidas'], ARRAY['Transporte ida y vuelta', 'Transporte marítimo', 'Almuerzo', 'Equipo de snorkeling', 'Guía especializado', 'Seguro']),

('Cayo Muerto', 'cayo-muerto', 'Tesoro escondido del Caribe venezolano', 'Explora el misterioso Cayo Muerto, un tesoro escondido con paisajes únicos y una atmósfera especial. Un destino perfecto para los aventureros.', 'Chichiriviche, Falcón', 125.00, '1 día (5:00 AM - 7:00 PM)', 'Plaza Venezuela, Caracas', 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=800&h=600&fit=crop', ARRAY['https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=800&h=600&fit=crop'], ARRAY['Paisajes únicos', 'Aventura extrema', 'Fotografía espectacular', 'Experiencia inolvidable'], ARRAY['Transporte ida y vuelta', 'Transporte marítimo', 'Almuerzo gourmet', 'Snacks', 'Guía turístico', 'Equipo de snorkeling']);

-- Destinos de Canaima
INSERT INTO public.destinations (name, slug, description, full_description, location, price, duration, departure_location, image_url, gallery_urls, highlights, includes) VALUES
('Salto Ángel', 'salto-angel', 'La cascada más alta del mundo', 'Visita el majestuoso Salto Ángel, la cascada más alta del mundo con 979 metros de altura. Una aventura épica que te dejará sin aliento, navegando por ríos y admirando tepuyes milenarios.', 'Canaima, Bolívar', 450.00, '3 días (5:00 AM día 1 - 8:00 PM día 3)', 'Plaza Venezuela, Caracas', 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&h=600&fit=crop', ARRAY['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&h=600&fit=crop'], ARRAY['Cascada más alta del mundo', 'Navegación por ríos', 'Vistas de tepuyes', 'Cultura indígena'], ARRAY['Transporte ida y vuelta', 'Vuelo a Canaima', 'Navegación fluvial', 'Todas las comidas', 'Alojamiento', 'Guía indígena', 'Seguro']),

('Recorrido Tepuyes', 'recorrido-tepuyes', 'Explora las montañas más antiguas del mundo', 'Descubre los tepuyes, las formaciones geológicas más antiguas de la Tierra. Un viaje por paisajes prehistóricos que te transportará millones de años atrás.', 'Canaima, Bolívar', 380.00, '2 días (5:00 AM día 1 - 7:00 PM día 2)', 'Plaza Venezuela, Caracas', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop', ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop'], ARRAY['Tepuyes milenarios', 'Paisajes prehistóricos', 'Flora endémica', 'Fotografía única'], ARRAY['Transporte ida y vuelta', 'Vuelo a Canaima', 'Todas las comidas', 'Alojamiento', 'Guía especializado', 'Equipo de trekking']),

('Laguna de Canaima', 'laguna-canaima', 'Laguna de aguas rojizas rodeada de cascadas', 'Relájate en la hermosa Laguna de Canaima, famosa por sus aguas rojizas únicas y las impresionantes cascadas que la rodean. Un oasis natural inolvidable.', 'Canaima, Bolívar', 280.00, '2 días (5:00 AM día 1 - 6:00 PM día 2)', 'Plaza Venezuela, Caracas', 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop', ARRAY['https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop'], ARRAY['Aguas rojizas únicas', 'Cascadas espectaculares', 'Baño en cascadas', 'Comunidades indígenas'], ARRAY['Transporte ida y vuelta', 'Vuelo a Canaima', 'Todas las comidas', 'Alojamiento campamento', 'Guía local', 'Actividades acuáticas']);

-- Destinos de Mérida  
INSERT INTO public.destinations (name, slug, description, full_description, location, price, duration, departure_location, image_url, gallery_urls, highlights, includes) VALUES
('Parque Nacional Sierra Nevada', 'parque-sierra-nevada', 'Naturaleza andina en su máxima expresión', 'Explora el Parque Nacional Sierra Nevada, hogar de los picos más altos de Venezuela. Disfruta de paisajes montañosos espectaculares, lagunas glaciares y páramos únicos.', 'Mérida', 180.00, '1 día (5:00 AM - 8:00 PM)', 'Plaza Venezuela, Caracas', 'https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?w=800&h=600&fit=crop', ARRAY['https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?w=800&h=600&fit=crop'], ARRAY['Picos nevados', 'Lagunas glaciares', 'Páramos andinos', 'Flora alpina'], ARRAY['Transporte ida y vuelta', 'Almuerzo típico andino', 'Chocolate caliente', 'Guía de montaña', 'Entrada al parque']),

('Pico el Águila', 'pico-el-aguila', 'El punto más alto de la carretera venezolana', 'Visita el icónico Pico el Águila a 4,118 metros de altura, el punto más alto accesible por carretera en Venezuela. Experimenta el frío de los Andes y vistas panorámicas impresionantes.', 'Mérida', 150.00, '1 día (5:00 AM - 7:00 PM)', 'Plaza Venezuela, Caracas', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop', ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop'], ARRAY['4,118 metros de altura', 'Vistas panorámicas', 'Clima de páramo', 'Monumento al Águila'], ARRAY['Transporte ida y vuelta', 'Desayuno andino', 'Almuerzo', 'Ropa térmica (opcional)', 'Guía turístico', 'Paradas fotográficas']);